# Generated by Django 4.2.17 on 2024-12-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('category', models.ManyToManyField(to='api.category')),
            ],
        ),
    ]
